exports.post = function (req, res) {
    //TODO: do your stuff here...
};

exports.modify = function (req, res) {
    //TODO: do your stuff here...
};
exports.delete = function (req, res) {
    //TODO: do your stuff here...
};
exports.getBookingInfo = function (req, res) {
    //TODO: do your stuff here...
};
exports.getBookingsByUser = function (req, res) {
    //TODO: do your stuff here...
};